### ISSUE TITLE
Problems if names or passwords contain spaces

### ISSUE THREAD

**Issue by brroberts1231** [cjleighton/Leighton_CSCI2270_FinalProject#1]
When creating an account, if the name you enter contains a space, the second word immediately becomes the password. For example, I entered "Ben Roberts" for a user name and Ben became the username and Roberts became the password, without it asking to set a password. Similarly, if you try to change a password to something that contains a space, it will only accept the first word. If I entered "word1 word2" to be the new password, only word1 would be used as the password.

**Comment by cjleighton** [comment]
Fixed.  Spaces are now handled correctly.

Edit: A better solution would have been to disallow spaces in usernames and passwords altogether, but I didn't do it, so oh well.
