### ISSUE TITLE
Menu does not re-display 

### ISSUE THREAD

**Issue by photobuff99** [cjleighton/Leighton_CSCI2270_FinalProject#2]
After a command is executed like "List all users" the menu does not display again.
![image](https://cloud.githubusercontent.com/assets/10749188/7446020/fa1cdbfe-f186-11e4-89fd-72ef73aaf551.png)

**Comment by cjleighton** [comment]
After you've listed all users or something, you're still actually on the main menu and you can enter commands.  It's set up in a way that it doesn't reprint the menu below as I've seen many other people's projects do.  Sorry for the confusion!
